theme: jekyll-theme-minimal
logo: https://avatars1.githubusercontent.com/u/1346014?s=460&v=4
title: Bertrand Svetchine
description: Computer engineer specialized in web development
google_analytics: UA-127846550-1
